### ISSUE TITLE
Add support for Services as Workload type

### ISSUE THREAD

**Issue by pipko** [pixel-point/kube-forwarder#10]
Service should be supported because it is the correct way to connect to pods inside the kubernetes. It solves the problem with the continuous deployment of some pods - now we need to always refresh pod's name in Kube Forward.

**Comment by proAlexandr** [comment]
Thank you that you let us know that it is demanded feature!
I have started to do it.
https://github.com/pixel-point/kube-forwarder/commit/1d9e69ed200a410301701507af372db4df83de0f

We are planning to release it soon, in v1.2.0

**Comment by lnikell** [comment]
@pipko That functionality now available in v1.2.0 together with a couple of new features:
- auto-complete of namespace/resource name
- cluster connection validation
