### ISSUE TITLE
Publish as Homebrew Cask

### ISSUE THREAD

**Issue by muenchdo** [pixel-point/kube-forwarder#11]
Hi,

this issue is more of an FYI that I just created the PR Homebrew/homebrew-cask#65781 to allow installing Kube Forwarder using Homebrew.

Cheers,
Dominik

**Comment by proAlexandr** [comment]
That's great! Thank you!

**Comment by lnikell** [comment]
@muenchdo Thank you for adding Kube Forwarder to brew cask! Am I right that it requires on each update, also publish changes in homebrew-cask catalog? Is it possible to set the latest version somehow or it is not a good approach?

I'm going to add in README.md information about installation via brew.

**Comment by muenchdo** [comment]
@lnikell Unfortunately I'm not super familiar with the process myself, but from what I can tell you currently need to publish the changes manually on every release.

**Comment by lnikell** [comment]
@muenchdo Thank you, we will try to keep it up to date
