### ISSUE TITLE
Load configs from file(s)

### ISSUE THREAD

**Issue by hsychla** [pixel-point/kube-forwarder#18]
I have dozens of cluster configs.
One file per cluster, not one huge `~/.kube/config`.

Instead of loading the config from one static location or have the user copy/paste the contents, it would be great if I could just tell the tool which file to open with an OpenFile Dialogue.

**Comment by lnikell** [comment]
Thank you @hsychla for the feedback, it's very interesting for us to know different use cases people have. We will think how could we manage properly that scenario.

**Comment by proAlexandr** [comment]
Hi, @hsychla. We have released [a new version](https://github.com/pixel-point/kube-forwarder/releases/tag/v1.4.0). Now, on the "Cluster Add" page, you can select multiple files with "Open a files(s)" button. I hope It will be useful for you.
Thanks for the idea that helped to make the app better!

**Comment by hsychla** [comment]
Awesome, thank you!
