### ISSUE TITLE
Unable to hit service 

### ISSUE THREAD

**Issue by streetmapp** [pixel-point/kube-forwarder#19]
The service I'm trying to hit is the argocd-server as deployed via this [walkthrough](https://argoproj.github.io/argo-cd/getting_started/). I am able to hit the service without issue when running the following: `kubectl port-forward svc/argocd-server -n argocd 8080:443
`. This is found under Step 3 in the above link.

I was able to configure my k3d cluster within kube-forwarder without issue. I went to add the service in question with the following details.

Namespace: argocd
Kind: service
Name: argocd-server
Ports Forwarding: Local - 8080 Resource - 443

I attempt to hit https://localhost:8080, but it times out.

**Comment by proAlexandr** [comment]
Hi @streetmapp, Thank you for the report. It looks like it has the same reason as https://github.com/pixel-point/kube-forwarder/issues/17 (Because Kube Forwarder doesn't map service ports)
If it is fixed by #17 patch in the next release, great! Otherwise, I will investigate it.

**Comment by proAlexandr** [comment]
Hi, @streetmapp! We've just released a [new version](https://github.com/pixel-point/kube-forwarder/releases/tag/v1.3.2), could you, please, check it?

**Comment by streetmapp** [comment]
Hi @proAlexandr, thanks for the quick turnaround on this. Just grabbed the latest and tested and it's working with the use case that I was having issues with before. This appears to have solved the problem!

Thanks again.
