### ISSUE TITLE
Autocomplete for deployments, pods and namespaces

### ISSUE THREAD

**Issue by lnikell** [pixel-point/kube-forwarder#2]
When user adds a new service we could fetch the list of namespaces, deployments and pods from Kubernetes API, and instead of typing in the input user will be able to pick one of the options
![image](https://user-images.githubusercontent.com/2697570/60106138-f4bc0f80-9764-11e9-8dc2-bacb26d0c368.png)

**Comment by Adiqq** [comment]
Remember to correctly handle permissions. In some cases, user might not have permission to list ns, deploy or pods. There should be combo boxes, so user can try to manual enter input in all cases.

**Comment by lnikell** [comment]
@Adiqq good point! Thank you!

**Comment by proAlexandr** [comment]
I have started to do.
https://github.com/pixel-point/kube-forwarder/commit/566cc51f58d1b012ad133f57e42f8da671dc0de8

**Comment by lnikell** [comment]
Added in v1.2.0
