### ISSUE TITLE
kube-forwarder.zip contains mac os package

### ISSUE THREAD

**Issue by konstantinwirz** [pixel-point/kube-forwarder#27]
Just downloaded linux package using this [ link](https://github.com/pixel-point/kube-forwarder/releases/latest/download/kube-forwarder.zip), unfortunately the archive contains only macos stuff...

**Comment by proAlexandr** [comment]
Hi @konstantinwirz, thanks for the issue.
It was a mistake in README. I have fixed it. The right link is https://github.com/pixel-point/kube-forwarder/releases/latest/download/kube-forwarder.AppImage
