### ISSUE TITLE
Blank white screen on startup

### ISSUE THREAD

**Issue by acukan** [pixel-point/kube-forwarder#3]
Hey, 

First of all thank you for your effort, 

I am using Macbook Pro 2018 with latest os version. When i open the app it just shows white screen.

**Comment by proAlexandr** [comment]
Hi @acukan, thank you for the bug report.
I have fixed it in 1.0.2.
https://github.com/pixel-point/kube-forwarder/releases/tag/v1.0.2

**Comment by acukan** [comment]
That problem gone, I am testing it now 👍
