### ISSUE TITLE
Verify connection to clusters

### ISSUE THREAD

**Issue by benfairless** [pixel-point/kube-forwarder#4]
When adding a cluster, I feel that next to the 'Save' button we should have a 'Verify' button which connects to the Kubernetes API.

Something like hitting `https://{{ KUBEAPI }}/healthz` and checking the response code. This could be used to validate if the API is reachable, the certificates are trusted, and whether the authentication is successful.

**Comment by lnikell** [comment]
Thank you for the idea @benfairless ! I think there is no need for verify button and it could become the part of the saving process.

**Comment by proAlexandr** [comment]
https://github.com/pixel-point/kube-forwarder/commit/f29d693a1387314a79b138c00cada8dd0681cbc0

**Comment by lnikell** [comment]
Added in v1.2.0 as a part of Save logic when you add a cluster. If there is a connection issue, we still allow you to add a cluster but throwing an alert. Separate button "Check connection" added to edit cluster page, as we expect it could be used for debug purpose if you decide manually adjust the configuration.
